female(aelia).
female(nabia).
male(arbaz).
male(huzaifa).
male(hannan).
male(kaseem).
male(hamza).
male(mubashir).
male(amir).
male(jaree).
male(umair).
male(abubakar).
father(arsalan,saima).
woman(saima).
likes(ali,icecream).
happy(ali).
friend(ali,farhan).
drive(farhan,car).
man(farhan).
walk(farhan).

